### PR TITLE
[TECHNICAL-SUPPORT] LPS-58384

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @arbetts

### CODE REVIEW

**Comment by johnnyhowey** [comment]
Is this going to be backported to 6.2?

**Comment by johnnyhowey** [comment]
If so, I will have to talk with the Loop team, because this might change our behaviors in Loop.

**Comment by arbetts** [comment]
Yes, the bug is reported in 6.2.10 so we should backport it.

for reference https://issues.liferay.com/browse/LPP-18027

**Comment by johnnyhowey** [comment]
Can I come downstairs and talk to you guys at 3pm? I think there is a better way to fix it.

**Comment by arbetts** [comment]
yes, please come on down

**Comment by johnnyhowey** [comment]
Pull request submitted at: https://github.com/brianchandotcom/liferay-plugins/pull/4928
View total diff: https://github.com/johnnyhowey/liferay-plugins/compare/8887bc074c...281f30a05b

**Pull request closed without merging**
