### PR TITLE
LPS-53122 Rename table in accordance with 6.2

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hey Jon,

Here is the pull that you wanted for Master. It's very different from the 6.2 fix because we're creating the table in 6.2 but then in Master, we're just reading from that table and then dropping it. If the fix for 6.2 gets source formatted and the table name is changed, this fix will also need to be changed.

Thanks.

### CODE REVIEW

**Comment by johnnyhowey** [comment]
Thanks!!! The reason I need to see this is so I can see the big picture. Of what we are doing.

**Comment by jonathanmccann** [comment]
Of course! I'll be sure to send both in tandem next time.

**Comment by johnnyhowey** [comment]
closing because of the error in ee-6.2.x, also I want to talk about the naming.

**Comment by johnnyhowey** [comment]
View total diff: https://github.com/johnnyhowey/liferay-plugins/compare/7f20f302ef...05cc6752ef

**Pull request closed without merging**
